title: Kolpinghaus Reutlingen
url: https://kolpinghaus-reutlingen.de
domain: kolpinghaus-reutlingen.de

destination: _site

commit: 6ba2da88d67c8287902bf6523cf0183bb8311032
image:
  url: https://res.cloudinary.com/kolpinghaus-rt/image/upload
  version: 1532618033
  option:
    default: c_lfill,g_auto,cs_srgb,q_auto
  max:
    w:
    h:

timezone: Europe/Berlin
future: true
excerpt_separator: <!--mehr-->

plugins:
   - jekyll-redirect-from

kontakt:
  city: 72764 Reutlingen
  street: Liststraße 26
  country: Deutschland
  phone: 07121 43340
  fax: 07121 43344
  email:
    plain: info@kolpinghaus-reutlingen.de
    user: info
  heimleiter: Hermann Rist
  hours:
    from: 8
    to: 17

author:
  name: Patrick Haußmann
  url: patrickhaussmann.de

google-site-verification: tyvNJr99qMKWyfVYXxuD8ikqOpWjCQfdJv5WvywBGqE

collections:
  artikel:
    output: true
  veranstaltungen:
    output: true
  projekte:
    output: true

defaults:
  - scope:
      path: ""
      type: artikel
    values:
      layout: post
      active: artikel
      permalink: /artikel/:path/
      img:
        folder: artikel
  - scope:
      path: ""
      type: veranstaltungen
    values:
      layout: post
      active: veranstaltungen
      permalink: /veranstaltung/:path/
      img:
        folder: veranstaltungen
  - scope:
      path: ""
      type: projekte
    values:
      layout: post
      active: projekte
      permalink: /projekt/:path/
      img:
        folder: projekte

exclude:
  - README.md
  - aktuelles.html
